version: '3.8'

services:
  nextjs:
    image: goodnumbers:latest
    container_name: goodnumbers_app_prod
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file:
      - .env.production
      - ../s/.env.secrets
    environment:
      - NODE_ENV=production
    volumes:
      # Mount the host key file to the container path (read-only)
      - /home/ssuppe/s/goodnumbersmain-446416-eff174c6bc72.json:/app/secrets/gcp-key.json:ro
