import './globals.css';

import type { Metadata } from 'next';
import { SITE } from '@/config.cjs';

// import { Geist, Geist_Mono } from "next/font/google";
import { Inter as CustomFont } from 'next/font/google';

import Providers from '@/components/atoms/Providers';
import Announcement from '@/components/widgets/Announcement';
import Header from '@/components/widgets/Header';
import Footer2 from '@/components/widgets/Footer2';

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

export interface LayoutProps {
  children: React.ReactNode;
}

export const metadata = {
  title: SITE.title,
};

const customFont = CustomFont({ subsets: ['latin'], variable: '--font-custom' });

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html
      lang="en"
      className={`motion-safe:scroll-smooth 2xl:text-[24px] ${customFont.variable} font-sans`}
      suppressHydrationWarning
    >
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body className="tracking-tight antialiased text-gray-900 dark:text-slate-300 dark:bg-slate-900">
        <Providers>
          <Announcement />
          <Header />
          <main>{children}</main>
          <Footer2 />
        </Providers>
      </body>
    </html>
  );
}
