'use client';

import WidgetWrapper from '@/components/atoms/WidgetWrapper';
import Headline from '@/components/atoms/Headline';

const Page = () => {
  const header = {
    title: 'Privacy Policy',
  };

  return (
    <>
      <WidgetWrapper hasBackground={true}>
        <Headline header={header} />
        <div className="max-w-3xl mx-auto">
          <div className="prose prose-lg dark:prose-invert prose-headings:font-bold prose-headings:text-primary-700 dark:prose-headings:text-primary-400 prose-p:text-gray-700 dark:prose-p:text-slate-300">
            <h2 className="text-xl font-semibold mt-8 mb-4">Privacy Policy for Goodnumbers</h2>
            <p className="mb-4">Last Updated: April 19, 2025</p>

            <p className="mb-4">
              Thank you for using Goodnumbers, a personal diabetes weekly journal that uses AI to help you identify
              trends and patterns in your diabetes data for reflection. At Goodnumbers, we are committed to protecting
              your privacy and being transparent about how your data is handled. Because your health information is
              sensitive, we want to be clear about what we do and, more importantly, what we{' '}
              <strong className="font-semibold">don't</strong> do with your personal data.
            </p>

            <h2 className="text-xl font-semibold mt-8 mb-4">1. Data Handling - Client-Side (Your Device)</h2>
            <p className="mb-4">
              The following information is stored securely <strong className="font-semibold">only</strong> on your
              device:
            </p>
            <ul className="list-disc pl-6 mb-4">
              <li>
                <strong className="font-semibold">Login Credentials:</strong> This includes information you provide to
                connect to your Nightscout instance, such as your Nightscout URL and API token. This information is used
                solely to retrieve your data and is not transmitted to our servers for permanent storage.
              </li>
              <li>
                <strong className="font-semibold">Preferred Glucose Units:</strong> Your chosen units for displaying
                glucose (e.g., mg/dL or mmol/L) are saved locally to personalize your experience.
              </li>
              <li>
                <strong className="font-semibold">Reports:</strong> Any reports, charts, or textual descriptions
                generated by Goodnumbers are created and stored directly on your device.
              </li>
            </ul>

            <h2 className="text-xl font-semibold mt-8 mb-4">2. Data Processing - Temporary Server-Side</h2>
            <p className="mb-4">
              Your{' '}
              <strong className="font-semibold">
                Nightscout data is sent to our servers and processed to identify trends and patterns
              </strong>
              , but it is <strong className="font-semibold">not saved</strong> on our servers with the exception of the
              audio overviews as described below.
            </p>

            <h2 className="text-xl font-semibold mt-8 mb-4">3. Data Storage - Server-Side (Goodnumbers' Servers)</h2>
            <p className="mb-4">
              The only data that is stored on Goodnumbers' servers is the{' '}
              <strong className="font-semibold">audio overview of your weekly report</strong>. Here's what you need to
              know about this:
            </p>
            <ul className="list-disc pl-6 mb-4">
              <li>
                <strong className="font-semibold">No Identifiable Information:</strong> The audio overview is designed
                to be completely anonymous. You are only referred to as "the patient," and no specific details that
                could identify you are included in the audio.
              </li>
              <li>
                <strong className="font-semibold">Hashed Filenames:</strong> The audio file and its associated RSS feed
                are saved with a unique, hashed filename. This hash is generated using your login credentials, which, as
                stated above, are only stored on your device. This means the filename cannot be easily guessed or linked
                back to you by anyone without your specific login information.
              </li>
              <li>
                <strong className="font-semibold">Podcast Subscription:</strong> This audio overview and its RSS feed
                allow you to listen to your weekly report through podcast apps.
              </li>
              <li>
                <strong className="font-semibold">Retention Period:</strong> Audio reports and their associated RSS
                files are stored on our servers for a maximum of <strong className="font-semibold">30 days</strong>.
                After this period, they are automatically and permanently deleted.
              </li>
            </ul>

            <h2 className="text-xl font-semibold mt-8 mb-4">4. Data Retention</h2>
            <ul className="list-disc pl-6 mb-4">
              <li>
                <strong className="font-semibold">Client-Side (Your Device):</strong> Your data is held on your device
                for <strong className="font-semibold">30 days</strong>. This allows you to easily access your recent
                weekly reports when you revisit the Goodnumbers page. You have the ability to{' '}
                <strong className="font-semibold">clear this data at any time</strong> through your browser's local
                storage settings. Please be aware that clearing this data will mean that the next time you visit
                Goodnumbers, your reports will need to be regenerated.
              </li>
              <li>
                <strong className="font-semibold">Server-Side (Goodnumbers' Servers):</strong> As mentioned above, audio
                reports are stored for a maximum of <strong className="font-semibold">30 days</strong> and then
                automatically deleted.
              </li>
            </ul>

            <h2 className="text-xl font-semibold mt-8 mb-4">
              5. Why We Process Data (and Why We Don't Store Most of It)
            </h2>
            <ul className="list-disc pl-6 mb-4">
              <li>
                <strong className="font-semibold">Server-Side Processing (Temporary):</strong> We temporarily receive
                and process your Nightscout data on our servers to generate your personalized weekly journal and
                insights. This processing is necessary to perform the AI analysis. However, we do not retain this raw
                data permanently.
              </li>
              <li>
                <strong className="font-semibold">Server-Side Processing (Audio Overview):</strong> The audio overview
                is generated to provide a convenient, hands-free way for you to review your weekly trends. By using
                hashed filenames and removing all identifiable information, we aim to offer this feature while
                maintaining your anonymity.
              </li>
            </ul>

            <h2 className="text-xl font-semibold mt-8 mb-4">6. Your Rights</h2>
            <p className="mb-4">
              Because we do not persistently store your personal Nightscout data on our servers (with the limited and
              anonymized exception of the audio overview for a short period), many traditional data privacy rights, such
              as the right to access, rectify, or erase personal data held by us, do not directly apply in the typical
              sense.
            </p>
            <p className="mb-4">However, you have full control over the data on your device:</p>
            <ul className="list-disc pl-6 mb-4">
              <li>
                <strong className="font-semibold">Access:</strong> You can see all the data processed and displayed by
                Goodnumbers directly on your device.
              </li>
              <li>
                <strong className="font-semibold">Control:</strong> You can clear the locally stored data at any time
                through your browser settings.
              </li>
              <li>
                <strong className="font-semibold">Deletion:</strong> By clearing your browser's local storage for the
                Goodnumbers website, you effectively delete all locally stored data. You can also choose not to generate
                or subscribe to the audio overview.
              </li>
            </ul>
            <h2 className="text-xl font-semibold mt-8 mb-4">7. Logging</h2>
            <p className="mb-4">
              To help us understand how Goodnumbers is being used and to debug any issues with the Service's
              functionality, we maintain logs of certain actions, such as calls to APIs and other internal processes.
            </p>
            <p className="mb-4">
              It's important to note that these logs <strong className="font-semibold">do not</strong> contain any of
              your personal Nightscout data or any other content you provide to the Service. The focus of these logs is
              on the technical operation of Goodnumbers itself.
            </p>
            <p className="mb-4">
              These logs are primarily used for internal purposes to ensure the Service is running smoothly and to
              identify and resolve any technical problems that may arise. We do not use these logs to track individual
              user behavior or to collect any personal information beyond what is necessary for debugging the
              application's functionality.
            </p>

            <h2 className="text-xl font-semibold mt-8 mb-4">7. Third-Party Services</h2>
            <p className="mb-4">
              Goodnumbers does not currently use any third-party tracking services, analytics tools, or advertising
              platforms that would collect your personal information.
            </p>

            <h2 className="text-xl font-semibold mt-8 mb-4">8. Changes to This Privacy Policy</h2>
            <p className="mb-4">
              We may update this Privacy Policy from time to time. Any changes will be posted on this page, and the
              "Last Updated" date will be revised. We encourage you to review this Privacy Policy periodically for any
              updates.
            </p>

            <h2 className="text-xl font-semibold mt-8 mb-4">9. Contact Us</h2>
            <p className="mb-4">
              If you have any questions or concerns about this Privacy Policy or how your data is handled, please feel
              free to reach out. Since this is a personal side project, the best way to contact me will be{' '}
              <a href="mailto:[Insert your preferred contact method here, e.g., email address]">
                [Insert your preferred contact method here, e.g., email address]
              </a>
              .
            </p>

            <p className="mb-4">
              By using Goodnumbers, you acknowledge that you have read and understood this Privacy Policy.
            </p>
          </div>
        </div>
      </WidgetWrapper>
    </>
  );
};

export default Page;
