// This file serves as the public API for the @goodnumbers/types package.
// It re-exports all the types generated by Prisma into a single, consumable module.
export type {
  User,
  Journal,
  GlycemicEventCluster,
  Account,
  Session,
  VerificationToken,
} from "./generated/client/index.js";

export type { JournalStatus, Json, GlucoseEntry } from "./api-types";

// --- Hotspot Engine Types ---
import { z } from "zod";
import {
  GlycemicEventSchema,
  GlycemicClusterSchema,
} from "@goodnumbers/schemas";

export type GlycemicEvent = z.infer<typeof GlycemicEventSchema>;
export type GlycemicCluster = z.infer<typeof GlycemicClusterSchema>;
