// This file serves as the public API for the @goodnumbers/types package.
// It re-exports all the types generated by Prisma into a single, consumable module.
export type {
  User,
  Journal,
  GlycemicEventCluster,
  Account,
  Session,
  VerificationToken,
} from "./generated/client/index.js";

export type { JournalStatus, Json, GlucoseEntry } from "./api-types.js";

// --- Enums ---
export * from "./enums.js";

// --- Hotspot Engine Types ---
// Defined manually to avoid dependency on Zod/Schemas

export interface GlucoseReading {
  timestamp: string;
  value: number;
}

export interface GlycemicEvent {
  id: string;
  type: "hyper" | "hypo";
  startTime: string;
  endTime: string;
  startMinuteOfDay: number;
  durationMinutes: number;
  readings: GlucoseReading[];
}

export interface GlycemicCluster {
  id: string;
  type: "hyper" | "hypo";
  avgStartMinute: number;
  avgDurationMinutes: number;
  eventCount: number;
  activeDays: number[]; // 1=Mon, 7=Sun
  events: GlycemicEvent[];
}

// --- Insights Types ---
export * from "./insights.js";

export interface Highlight {
  type: "win" | "warn" | "trend";
  icon: string;
  title: string;
  short_description: string;
}
