"""File for loading data. Right now this only includes importing from known local files"""
import json

import mypandas as pd
from bgpodcast.utils import bgutils

def read_treatments_file(fpath : str) -> list:
    """ 
    Return a list of dicts in the same format as the next.js/fastapi app

    Args:
        fpath (str): path to file to read

                (item: { date: number; carbs?: number; utcOffset: number; insulin?: number; eventType: string }) => ({

    Returns:
        list: in same format as webapp
    """
    with open(fpath, "r", encoding="utf-8") as f:
        e = f.read()
        e = json.loads(e)
        treatments = []
        for entry in e:
            try:

                date = int(entry["date"])
                utcOffset = int(entry["utcOffset"])
                carbs = entry["carbs"]
                if carbs is not None:
                    carbs = int(carbs)
                
                insulin = entry["insulin"]
                if insulin is not None:
                    insulin = int(insulin)

                eventType = entry["eventType"]

                treatments.append({"date" : date, "utcOffset" : utcOffset, "carbs" : carbs, "insulin" : insulin, "eventType" : eventType})
            except Exception as e:
                print(f"Error in line: {entry}")
                raise(e)
        
        return treatments
    
    return []

def read_entries_file(fpath : str) -> list:
    """ 
    Return a list of dicts in the same format as the next.js/fastapi app
    [{'date': 1733147724000, 'sgv': 90, 'units': 'mg/dl', 'utcOffset': -480},...]

    Args:
        fpath (str): path to file to read

    Returns:
        list: in same format as webapp
    """
    with open(fpath, "r", encoding="utf-8") as f:
        e = f.read()
        e = json.loads(e)
        entries = []
        for entry in e:
            try:
                entries.append({"date" : int(entry["date"]), "utcOffset" : int(entry["utcOffset"]), "sgv" : int(entry["sgv"])})
            except Exception as e:
                print(f"Error in line: {entry}")
                raise(e)
        
        return entries
    
    return []

def load_sgv_dict(d : dict) -> pd.DataFrame:
    """
        Load insulin information and sgv information from nightscout - entries API
    """
    entries = pd.DataFrame.from_dict(d)
    # From JSON, create entriesset

    entries["date"] = entries.apply(lambda x: bgutils.create_date_from_timestamp(x["date"]//1000, x["utcOffset"]), axis=1)
    # entries.append([bgutils.create_date_from_timestamp(j['date']//1000, j['utcOffset']),j['sgv']])
    
    # entries = pd.DataFrame(entries)
    # print(entries.head())
    # entries.columns = ["date", "sgv"] #, "direction"]

    # Get rid of seconds precision, and round to nearest 5 minutes
    # entries['date'] = entries['date'].dt.floor('min').dt.round("5min")
    # entries.head()
    
    ###############################################
    # Device status entries have IOB data
    # First, basic data ingestion and date parsing
    # with open(f"./data/{sub_dir}/Nightscout.devicestatus.{key}.json", "r", encoding="utf-8") as f:
    #     js = json.load(f)
        
    # devicestatus = []
    # # From JSON, create dataset
    # # display(js[0])
    # for j in js:
    #     if 'openaps' not in j:
    #         continue
        
    #     iob = None
    #     if 'iob' in j['openaps']:
    #         iob = j['openaps']['iob']['iob']
        
    #         basaliob = None
    #         if 'basaliob' in j['openaps']['iob']:
    #             basaliob = j['openaps']['iob']['basaliob']
        
    #         activity = None
    #         if 'activity' in j['openaps']['iob']:
    #             activity = j['openaps']['iob']['activity']
        
    #         devicestatus.append([create_date_from_timestamp(j['date'], j['utcOffset']), iob, basaliob, activity ])
    
    # devicestatus = pd.DataFrame(devicestatus)
    # devicestatus.columns = ["date", "iob", "basaliob", "activity"]
    # # Get rid of seconds precision, and round to nearest 5 minutes
    # # devicestatus['date'] = devicestatus['date'].dt.floor('min').dt.round("5min")

    # results = pd.merge(entries, devicestatus, left_on='date', right_on='date', how='inner')
    # return results
    return entries[["date", "sgv"]]

def load_carb_dict(d : dict) -> pd.DataFrame:
    """
    Load carb data from a JSON object generated by the Nightscout entries API
    """
    # print(jsono)
    # treatments = []
    # for j in jsono:
    #     if j["isValid"] is True and "carbs" in j and j["carbs"] is not None:
    #         carbs = j["carbs"]
    #         utcoffset = int(j["utcOffset"])
    #         date = datetime.datetime.strptime(j["created_at"][0:10], "%Y-%m-%d") + pd.Timedelta(minutes=utcoffset)
    #         treatments.append([date, carbs])
    
    treatments = pd.DataFrame.from_dict(d)
    treatments["date"] = treatments.apply(lambda x: bgutils.create_date_from_timestamp(x["date"]//1000, x["utcOffset"]), axis=1)
    treatments = treatments[["date", "carbs"]]
    treatments = treatments.dropna()
    return treatments


